name: Build and test ğŸ—ğŸ§ª

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: |
            docker run --name Redis --publish 6379:6379 --detach redis:latest
            cp .env.example .env
            echo "Installing dependencies âŒ›ï¸"
            npm ci
            npm i knex
    - run: |
            echo "Building the client ğŸ§±"
            npm run build --if-present
    - run: |
            echo "Linting the code ğŸ‘€"
            npm run lint
    - run: |
            echo "Running the tests ğŸ§ª"
            sudo systemctl start mysql.service
            sudo mysql -e 'DROP DATABASE IF EXISTS deployer;' -proot
            sudo mysql -e 'CREATE DATABASE deployer;' -proot
            npx knex migrate:latest
            npm test
